name: myfitbro
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  formz: ^0.6.1
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  intl: any
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.4
  supabase_flutter: ^2.3.2
  uni_links: ^0.5.1
  validators: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.10
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:

  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/local.config.json
    - google_fonts/montserrat_alternates/

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios: null

  flavors:
    local:
      app:
        name: "myfitbro Local"

      android:
        applicationId: "com.artis.myfitbro.local"
      ios:
        bundleId: "com.artis.myfitbro.local"

    development:
      app:
        name: "myfitbro Development"

      android:
        applicationId: "com.artis.myfitbro.dev"
      ios:
        bundleId: "ccom.artis.myfitbro.dev"

    production:
      app:
        name: "myfitbro Production"

      android:
        applicationId: "com.artis.myfitbro"
      ios:
        bundleId: "com.artis.myfitbro"
